config/routes.rb
Rails.application.routes.draw do

  root "events#index"

  get "events/filter/:filter" => "events#index", as: :filtered_events

  resources :events do # Rails makes all routes for event with one line
    resources :registrations #makes events/id/registrations
    resources :likes
  end

  resources :users
  get "signup" => "users#new"

  resource :session, only: [:create, :new, :destroy]

  # get "events" => "events#index"
  # post "events/new" => "events#create"
  # get "events/:id" => "events#show", as: "event"
  # get "events/:id/edit" => "events#edit", as: "edit_event"
  # patch "events/:id" => "events#update"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :registrations, dependent: :destroy #cascades delete of children
  has_many :likes, dependent: :destroy

  has_many :likers, through: :likes, source: :user

  validates :name, :location, presence: true
  validates :description, length: { minimum: 25 }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
  validates :capacity,
      numericality: { only_integer: true, greater_than: 0 }

  validates :image_file_name, format: {
    with: /\w+\.(jpg|png)\z/i,
    message: "must be a jpg or png"
  }

  scope: :past, -> { where("starts_at < ?", Time.now).order("starts_at desc") }
  scope: :upcoming, -> { where("starts_at > ?", Time.now).order("starts_at desc") }
  scope: :free, -> { upcoming.where(price: 0.0).order(:name) }
  scope: :recent, ->(max=3) { past.limit(max) }

  def free?
    self.price != 0 || price.blank?
  end

  def sold_out?
    (capacity - registrations.size).zero?
  end

  def self.upcoming
    where("starts_at > ?", Time.now).order("starts_at desc")
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event
  belongs_to :user

  HOW_HEARD_OPTIONS = [
    'Newsletter',
    'Blog Post',
    'Twitter',
    'Web Search',
    'Friend/Coworker',
    'Other'
  ]

  validates :how_heard,
    inclusion: { in: HOW_HEARD_OPTIONS }


end

app/models/user.rb
class User < ApplicationRecord
  has_many :registrations, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :liked_events, through: :likes, source: :event

  has_secure_password

  validates :name, presence: true

  validates :email, format: { with: /\S+@\S+/ },
      uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def require_sign_in
    unless current_user
      session[:intended_url] = request.url
      redirect_to new_session_url, alert: "Please sign in first."
    end
  end

  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end

  def current_user?(user)
    current_user == user
  end

  def require_admin
    unless current_user_admin?
      redirect_to events_url, alert: "Unauthorized"
    end
  end

  def current_user_admin?
    current_user && current_user.admin?
  end

  helper_method :current_user_admin?
  helper_method :current_user
  helper_method :current_user?

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :require_sign_in, except: [:show, :index]
  before_action :require_admin, except: [:show, :index]

  def index
    @age = rand(100)
    case params[:filter]
    when "past"
      @events = Event.past
    when "free"
      @events = Event.free
    when "recent"
      @events = Event.recent
    else
      @events = Event.upcoming
    end
  end

  def destroy
    @event = Event.find(params[:id])
    if @event.destroy
      redirect_to events_url, alert: "Movie removed!"
    else
      render :edit
    end
  end

  def show
    @event = Event.find(params[:id])
    @likers = @event.likers
    if current_user
      @like = current_user.likes.find_by(event_id: @event.id)
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(event_params)
      redirect_to event_path, notice: "Event updated!"
    else
      render :edit
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event), notice: "Event created!"
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event)
      .permit(:name, :description, :location, :price, :starts_at, :capacity, :image_file_name)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :require_sign_in

  def create
    @event = Event.find(params[:event_id])
    @event.likes.create!(user: current_user)
    redirect_to @event
  end

  def destroy
    like = current_user.likes.find(params[:id])
    like.destroy

    event = Event.find(params[:event_id])

    redirect_to @event
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :require_sign_in
  before_action :set_event

  def index
    @registrations = @event.registrations
  end

  def new
    @registration = @event.registrations.new
  end

  def create
    @registration = @event.registrations.new(registration_params)
    @registration.user = current_user

    if @registration.save
      redirect_to event_registrations_url(@event), notice: "Thanks for registering"
    else
      render :new
    end
  end

  private

  def registration_params
    params.require(:registration).permit(:how_heard)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to (session[:intended_url] || user), notice: "welcome back, #{user.name}!"
      session[:intended_url] = nil
    else
      flash.now[:alert] = 'Invalid email or password.'
      render :new
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to events_url, notice: "You have been logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # order matters here
  before_action :require_sign_in, except: [:new, :create]
  before_action :require_correct_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @registrations = @user.registrations
    @liked_events = @user.liked_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "Thanks for signing up"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: "You can edit!"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy(user_params)
    session[:user_id] = nil
    redirect_to events_url, alert: "You gone boii!"
  end

  private

  def require_correct_user
    @user = User.find(params[:id])
    redirect_to events_url unless @user == current_user
  end

  def user_params
    params.require(:user).
      permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def price(event)
    if event == 0 || event.price == nil
      "Free"
    else
      number_to_currency(event.price, precision: 0)
    end
  end

  def day_and_time(event)
    event.starts_at.strftime("%B %d at %I:%M %P")
  end
end

app/helpers/likes_helper.rb
module LikesHelper
  def like_or_unlike_button(event, like)
    if like
      button_to "Unlike!", event_like_path(event, like), method: :delete
    else
      button_to "Like!", event_likes_path(event)
    end
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper

  def register_or_sold_out(event)
    if event.sold_out?
      content_tag(:span, "Sold out!", class: "sold-out")
    else
      link_to "Register", new_event_registration_path(event), class: "register"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
    <%= render "shared/errors", object: event %>

    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 5 %>

    <%= f.label :location %>
    <%= f.text_field :location %>

    <%= f.label :price %>
    <%= f.text_field :price %>

    <%= f.label :starts_at %>
    <%= f.datetime_select :starts_at, {ampm: true}, {class: "datetime"} %>

    <%= f.label :capacity %>
    <%= f.number_field :capacity %>

    <%= f.label :image_file_name %>
    <%= f.text_field :image_file_name %>

    <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>
    Editing <%= @event.name %>
</h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<% @events.each do |event| %>
    <section class="event">
        <div class="image">
            <%= image_tag event.image_file_name %>
        </div>
        <div class="summary">


            <strong><%= link_to event.name, event_path(event) %></strong>
            in <%= event.location %>:
            <%= price(event) %>
            <p><%= event.description %></p>
            <p>Starts at: <%= day_and_time(event) %></p>

        </div>
    </section>
<% end %>
<% if current_user_admin? %>
  <section class="admin">
      <%= link_to "Add New Event", new_event_path, class: "button" %>
  </section>
<% end %>

app/views/events/new.html.erb
<h1>Create a new event<h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<section class="event">
    <div class="image">
        <%= image_tag @event.image_file_name %>
    </div>
    <div class="summary">

    <% if current_user %>
        <div class="likes">
            <%= like_or_unlike_button(@event, @like) %>

            <div class="count">
                <%= @likers.size %>
            </div>
        </div>
    <% end %>

    <strong><%= @event.name %></strong>
    in <%= @event.location %>:
    <%= pluralize(@event.capacity, "spot") %> &bull; <%= price(@event) %>
    <p><%= @event.description %></p>
    <div class="register">
        <%= register_or_sold_out(@event) %>
        <%= link_to "Whos registered?", event_registrations_path(@event), class: "button" %>
    </div>
    <p>Starts at: <%= day_and_time(@event) %></p>
</div>
</section>

<% if current_user_admin? %>
    <section class="admin">
        <%= link_to "Edit", edit_event_path(@event), class: "button" %>
        <%= button_to "Delete", @event, class: "button", method: :delete %>
    </section>
<% end %>

<aside>
    <% if @likers.present? %>
        <h4>liked by</h4>
        <ul>
            <% @likers.each do |user| %>
                <li>
                    <%= link_to user.name, user %>
                </li>
            <% end %>
        </ul>
    <% end %>
</aside>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<header>
    <nav>
      <%= link_to image_tag("logo"), root_path %>
      <ul class="left">
        <li>
          <%= link_to "Upcoming", events_path %>
        </li>
        <li>
          <%= link_to "Past", filtered_events_path(:past) %>
        </li>
        <li>
          <%= link_to "Free", filtered_events_path(:free) %>
        </li>
        <li>
          <%= link_to "Recent", filtered_events_path(:recent) %>
        </li>
      </ul>
      <ul class="right">
        <% if current_user %>
          <li>
            <%= link_to current_user.name, current_user %>
          </li>
          <li>
            <%= link_to "Sign out!", session_path, method: "delete", class: "button"%>
          </li>
        <% else %>
          <li>
            <%= link_to "Sign In", new_session_path, class: "button" %>
          </li>
          <li>
            <%= link_to "Sign Up", signup_path, class: "button" %>
          </li>
        <% end %>
      </ul>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <%= render "layouts/header" %>

  <body>
    <%= render "layouts/flash" %>
    <%= yield %>
  </body>

  <%= render "layouts/footer" %>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
    <%= render "shared/errors", object: user %>

    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
    <%= f.submit "Create Account" %>
  <% else %>
    <%= f.submit "Create Account" %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit account</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>

<ul class="users">
    <% @users.each do |user| %>
        <li>
            <%= link_to user.name, user %>
            created
            <%= time_ago_in_words(user.created_at) %> ago
        </li>
    <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>
  <% if current_user?(@user) %>
    <div class="actions">
      <%= link_to "Edit account", edit_user_path(@user), class:"button edit" %>
    </div>
  <% end %>
  <% if @registrations.present? %>
    <h3>Registrations</h3>
    <% @registrations.each do |r| %>
      <div class="registration">
        <div class="image">
          <%= link_to image_tag(r.event.image_file_name), r.event %>
        </div>
        <div class="name">
          <%= link_to r.event.name, r.event %>
        </div>
        <div class="date">
          <%= time_ago_in_words(r.created_at) %> ago
        </div>
      </div>
    <% end %>
  <% end %>
</section>


    <% if @liked_events.present? %>
        <h4>liked events</h4>
        <div class="liked-events">
            <% @liked_events.each do |event| %>
                <li>
                    <%= link_to image_tag(event.image_file_name), event %>
                </li>
            <% end %>
        </div>
    <% end %>